import type { NextPage } from "next";
import Head from "next/head";
import * as React from "react";
import Image from "next/image";
import { Button } from "@/components/elements/Button";
import styles from "@/styles/pages/Home.module.css";

const Monkeys = () => {
  const [num, setNum] = React.useState(0)
  console.log("Monkeys render");
  return(
    <div>
      <p>There are {num} monkeys.</p>
      <button onClick={() => setNum(num + 1)}>Add one monkey</button>
      <button onClick={() => setNum(num - 1)}>Subtract one monkey</button>
    </div>
  )
}

const Home: NextPage = () => {
  console.log("Home render");
    return (
        <div className={styles.Container}>
            <Head>
                <title>Fernando Blog</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/images/favicon.ico" />
            </Head>

            <main className={styles.Main}>
                <h1 className={styles.Title}>
                    Welcome to Fernandos Blog Project
                </h1>
                <Button />
                <Monkeys />
            </main>
        </div>
    );
};

export default Home;
