import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Button } from "@/components/elements/Button";
import styles from "@/styles/pages/Home.module.css";

const Home: NextPage = () => {
    return (
        <div className={styles.Container}>
            <Head>
                <title>Fernando Blog</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/images/favicon.ico" />
            </Head>

            <main className={styles.Main}>
                <h1 className={styles.Title}>
                    Welcome to Fernandos Blog Project
                </h1>
                <Button />
            </main>
        </div>
    );
};

export default Home;
